### ISSUE TITLE
Error in loading pretrained roadnet weights

### ISSUE THREAD

**Issue by mribrahim** [yhlleo/DeepSegmentor#10]
File: base_model.py Line 197

Error in net.load_state_dict(state_dict)  

dataset [RoadNetDataset] was created
initialize network with xavier
model [RoadNetModel] was created
loading the model from ./checkpoints/roadnet/pretrained_net_G.pth
Traceback (most recent call last):
  File "test.py", line 20, in <module>
    model.setup(opt)               # regular setup: load and print networks; create schedulers
  File "/home/ibrahim/Desktop/Research/DeepSegmentor/models/base_model.py", line 88, in setup
    self.load_networks(load_suffix)
  File "/home/ibrahim/Desktop/Research/DeepSegmentor/models/base_model.py", line 197, in load_networks
    net.load_state_dict(state_dict)
  File "/home/ibrahim/anaconda3/envs/env-yolo/lib/python3.7/site-packages/torch/nn/modules/module.py", line 847, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for RoadNet:
	Unexpected key(s) in state_dict: "segment_conv1.1.weight", "segment_conv1.1.bias", "segment_conv1.4.weight", "segment_conv1.4.bias", "segment_conv2.1.weight", "segment_conv2.1.bias", "segment_conv2.4.weight", "segment_conv2.4.bias", "segment_conv3.1.weight", "segment_conv3.1.bias", "segment_conv3.4.weight", "segment_conv3.4.bias", "segment_conv3.7.weight", "segment_conv3.7.bias", "segment_conv4.1.weight", "segment_conv4.1.bias", "segment_conv4.4.weight", "segment_conv4.4.bias", "segment_conv4.7.weight", "segment_conv4.7.bias", "segment_conv5.1.weight", "segment_conv5.1.bias", "segment_conv5.4.weight", "segment_conv5.4.bias", "segment_conv5.7.weight", "segment_conv5.7.bias", "edge_conv1.1.weight", "edge_conv1.1.bias", "edge_conv1.4.weight", "edge_conv1.4.bias", "edge_conv2.1.weight", "edge_conv2.1.bias", "edge_conv2.4.weight", "edge_conv2.4.bias", "edge_conv3.1.weight", "edge_conv3.1.bias", "edge_conv3.4.weight", "edge_conv3.4.bias", "edge_conv4.1.weight", "edge_conv4.1.bias", "edge_conv4.4.weight", "edge_conv4.4.bias", "centerline_conv1.1.weight", "centerline_conv1.1.bias", "centerline_conv1.4.weight", "centerline_conv1.4.bias", "centerline_conv2.1.weight", "centerline_conv2.1.bias", "centerline_conv2.4.weight", "centerline_conv2.4.bias", "centerline_conv3.1.weight", "centerline_conv3.1.bias", "centerline_conv3.4.weight", "centerline_conv3.4.bias", "centerline_conv4.1.weight", "centerline_conv4.1.bias", "centerline_conv4.4.weight", "centerline_conv4.4.bias". 
	size mismatch for side_segment_conv1.weight: copying a param with shape torch.Size([1, 64, 1, 1]) from checkpoint, the shape in current model is torch.Size([3, 64, 1, 1]).
	size mismatch for side_segment_conv2.weight: copying a param with shape torch.Size([1, 128, 1, 1]) from checkpoint, the shape in current model is torch.Size([3, 128, 1, 1]).
	size mismatch for side_segment_conv3.weight: copying a param with shape torch.Size([1, 256, 1, 1]) from checkpoint, the shape in current model is torch.Size([3, 256, 1, 1]).
	size mismatch for side_segment_conv4.weight: copying a param with shape torch.Size([1, 512, 1, 1]) from checkpoint, the shape in current model is torch.Size([3, 512, 1, 1]).
	size mismatch for side_segment_conv5.weight: copying a param with shape torch.Size([1, 512, 1, 1]) from checkpoint, the shape in current model is torch.Size([3, 512, 1, 1]).
	size mismatch for fuse_segment_conv.weight: copying a param with shape torch.Size([1, 5, 1, 1]) from checkpoint, the shape in current model is torch.Size([3, 15, 1, 1]).
	size mismatch for edge_conv1.0.weight: copying a param with shape torch.Size([32, 4, 3, 3]) from checkpoint, the shape in current model is torch.Size([32, 6, 3, 3]).
	size mismatch for side_edge_conv1.weight: copying a param with shape torch.Size([1, 32, 1, 1]) from checkpoint, the shape in current model is torch.Size([3, 32, 1, 1]).
	size mismatch for side_edge_conv2.weight: copying a param with shape torch.Size([1, 64, 1, 1]) from checkpoint, the shape in current model is torch.Size([3, 64, 1, 1]).
	size mismatch for side_edge_conv3.weight: copying a param with shape torch.Size([1, 128, 1, 1]) from checkpoint, the shape in current model is torch.Size([3, 128, 1, 1]).
	size mismatch for side_edge_conv4.weight: copying a param with shape torch.Size([1, 256, 1, 1]) from checkpoint, the shape in current model is torch.Size([3, 256, 1, 1]).
	size mismatch for fuse_edge_conv.weight: copying a param with shape torch.Size([1, 4, 1, 1]) from checkpoint, the shape in current model is torch.Size([3, 12, 1, 1]).
	size mismatch for centerline_conv1.0.weight: copying a param with shape torch.Size([32, 4, 3, 3]) from checkpoint, the shape in current model is torch.Size([32, 6, 3, 3]).
	size mismatch for side_centerline_conv1.weight: copying a param with shape torch.Size([1, 32, 1, 1]) from checkpoint, the shape in current model is torch.Size([3, 32, 1, 1]).
	size mismatch for side_centerline_conv2.weight: copying a param with shape torch.Size([1, 64, 1, 1]) from checkpoint, the shape in current model is torch.Size([3, 64, 1, 1]).
	size mismatch for side_centerline_conv3.weight: copying a param with shape torch.Size([1, 128, 1, 1]) from checkpoint, the shape in current model is torch.Size([3, 128, 1, 1]).
	size mismatch for side_centerline_conv4.weight: copying a param with shape torch.Size([1, 256, 1, 1]) from checkpoint, the shape in current model is torch.Size([3, 256, 1, 1]).
	size mismatch for fuse_centerline_conv.weight: copying a param with shape torch.Size([1, 4, 1, 1]) from checkpoint, the shape in current model is torch.Size([3, 12, 1, 1]).

**Comment by metaism-ding** [comment]
I met the same problem. I solved it by setting parameter 
```
net.load_state_dict(new_state_dict, strict=False)
```
in base_model.py.

**Comment by yhlleo** [comment]
Is it a problem of different pytorch versions? @metaism-ding @mribrahim

**Comment by mribrahim** [comment]
Installed torch version is 1.5.1

**Comment by yhlleo** [comment]
OK, it's 0.4.1 in [`environment.yml`](https://github.com/yhlleo/DeepSegmentor/blob/master/environment.yml)
