### ISSUE TITLE
Prediction to image

### ISSUE THREAD

**Issue by lfangyu09** [yhlleo/DeepSegmentor#14]
Hi,

Thanks a lot for providing this very useful code. I have a question about your code. Because I saw you used different thresholds to binarize the predicted image, I wonder how the prediction is changed to an image?  prediction of the model -> sigmoid -> *255 to array -> image?  Thanks!

**Comment by yhlleo** [comment]
Hi, @lfangyu09  

Do you mean that how we get the predicted images? 

If yes, we call the function [`model.test()`](https://github.com/yhlleo/DeepSegmentor/blob/master/test.py#L31) first, which indeed run `forward()`.  Then you can find the predicted results from the model: [codes](https://github.com/yhlleo/DeepSegmentor/blob/master/models/deepcrack_model.py#L87-L93). Given the outputs of `sigmoid` function are with the range of [0, 1], I transformed it to be with the range of [-1, 1] ([util. tensor2im](https://github.com/yhlleo/DeepSegmentor/blob/master/util/util.py#L9) requires the input images are with the range [-1, 1]).

In this inference procedure, we don't binarize the image with any thresholds. The thresholds are selected through the PR curve in the evaluation procedure.

**Comment by lfangyu09** [comment]
Hi,

Thanks a lot for your reply. If you change the outputs into the range of [-1,1], how do you save these outputs into images? Because I want to evaluate the output by using precision, recall, and so on. Thanks!

**Comment by yhlleo** [comment]
[util.tensor2im](https://github.com/yhlleo/DeepSegmentor/blob/master/util/util.py#L24) converts the image with the range of [-1, 1] to [0, 255]. 

Then, you can evaluate the precision and recall with the saved images.
