### ISSUE TITLE
modifications made after paper publication

### ISSUE THREAD

**Issue by luspectabilis** [yhlleo/DeepSegmentor#15]
Hi! I find that the crack segmentation results downloaded from google drive are much better than those in your paper. For example, iou is improved from 85.9 to 87.8. What modifications did you make after paper publication?

**Comment by yhlleo** [comment]
Hi, the original implementation was based on Caffe. During moving to the pytorch version, there are two main differences: (1) I don't use data augmentation as the original paper; (2) I adjust the loss terms to BinaryFocalLoss.  @luspectabilis
