### ISSUE TITLE
Colab version

### ISSUE THREAD

**Issue by ZurMaD** [yhlleo/DeepSegmentor#16]
Hello there I created a simple Colab Notebook to run DeepCrack inference

https://colab.research.google.com/drive/1t2C5mBOy7xuB4kP9TQzVOI0nglJBkMMD?usp=sharing

Please consider to add to your docs, thanks in advance

**Comment by yhlleo** [comment]
Thanks! It's awesome! I'll add a link in my docs. @ZurMaD

**Comment by yhlleo** [comment]
I added it into Acknowledgment. Thanks again!

**Comment by dlercier** [comment]
Thanks @ZurMaD for your Colab Notebook ! It is great to start.
I tryed to adapt it for the RoadNet model, but I failed to get it to work on the demo image : 

https://colab.research.google.com/drive/1zMNTJ1EP8FiHC-o9YQ2NGJuytb2emiAf?usp=sharing

The result folder is empty with this code.

Does anyone know how to get a result ?

Thank you for your help.

**Comment by ZurMaD** [comment]
> Thanks @ZurMaD for your Colab Notebook ! It is great to start.
> I tryed to adapt it for the RoadNet model, but I failed to get it to work on the demo image :
> 
> https://colab.research.google.com/drive/1zMNTJ1EP8FiHC-o9YQ2NGJuytb2emiAf?usp=sharing
> 
> The result folder is empty with this code.
> 
> Does anyone know how to get a result ?
> 
> Thank you for your help.

Hello @dlercier I create the notebook for deepcrack only, but maybe I'll take a closer look this weekend to adapt to RoadNet :)

**Comment by ZurMaD** [comment]
Hello @dlercier I fixed the colab to support both networks, I'll also create a PR to update to the last one.

https://colab.research.google.com/drive/13qSMnU1ERU7riHMMiv9MEEr7VTMhfZs9?usp=sharing

**Comment by dlercier** [comment]
Thank you @ZurMaD. 
I didn't understand that manual annotation of road surface, edge and centerline are expected as inputs.
