### ISSUE TITLE
Web version

### ISSUE THREAD

**Issue by ZurMaD** [yhlleo/DeepSegmentor#17]
Hello there,

I forked the project to create a web app deployed on Heroku free tier to be easy to use as a DEMO of your work. 

Some considerations:
- Only cpu inference (image[png/jpg/jpeg/bmp] and video[mp4] allowed)
- Automatic resizing input images and video frames (500px).
- Only DeepCrack
- "_fused" images taken as output

Web version https://deepcrackcpu.herokuapp.com/
Repo of web version https://github.com/DZDL/crack-detector

**Comment by yhlleo** [comment]
Awesome! I added it to the Acknowledgment. Thanks a lot! @ZurMaD
