### ISSUE TITLE
pytorch=0.4.1

### ISSUE THREAD

**Issue by codeeppy** [yhlleo/DeepSegmentor#2]
_C:\dl\Repository\Others\DeepSegmentor-master>conda env create -f environment.yml

Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound:
  - pytorch=0.4.1_

Hello,
I am trying to implement the model for a custom dataset but I am having the aforementioned issue. Although I have pytorch=1.1.0 in my own virtual env,  even then I am getting an assertion error as below:

_(myenv) C:\dl\Repository\Others\DeepSegmentor-master>python ./tools/calculate_weights.py --data_path C:\dl\Repository\Others\DeepSegmentor-master\tools
{}
Traceback (most recent call last):
  File "./tools/calculate_weights.py", line 60, in <module>
    print(reverse_weight(weights))
  File "./tools/calculate_weights.py", line 43, in reverse_weight
    assert len(w) > 0, "Expected a non-empty weight dict."
AssertionError: Expected a non-empty weight dict._

What should I do to solve this?

**Comment by yhlleo** [comment]
It seems that you run the command in a Windows system, right? 
As I know, the command works for Ubuntu server well.

You can try with pytorch=1.1.0 version in you virtual env. 
If there are some other problems, please let me know.

**Comment by yhlleo** [comment]
For the `calculate_weights.py`, I guess it's the problem of data path. Do you set the parameter in a right way? Please check it again.

**Comment by codeeppy** [comment]
Thank you for your suggestion.
As I was running the commands on the Windows system, there was some path and --dataroot issues.
But it finally worked..
