### ISSUE TITLE
issue when training the model 

### ISSUE THREAD

**Issue by ZheningHuang** [yhlleo/DeepSegmentor#21]
```
Traceback (most recent call last):
  File "train.py", line 32, in <module>
    model.optimize_parameters(epoch)   # calculate loss functions, get gradients, update network weights
  File "/rds/project/t2_vol2/rds-t2-cs056/ll610/Onepiece/zh_data/DeepSegmentor/models/deepcrack_model.py", line 115, in optimize_parameters
    self.backward()             # calculate gradients for G
  File "/rds/project/t2_vol2/rds-t2-cs056/ll610/Onepiece/zh_data/DeepSegmentor/models/deepcrack_model.py", line 103, in backward
    self.loss_side += self.criterionSeg(out, self.label) * w
  File "/home/ll610/miniconda3/envs/deepsegmentor/lib/python3.5/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/rds/project/t2_vol2/rds-t2-cs056/ll610/Onepiece/zh_data/DeepSegmentor/models/deepcrack_networks.py", line 103, in forward
    BCE_loss = self.criterion(inputs, targets)
  File "/home/ll610/miniconda3/envs/deepsegmentor/lib/python3.5/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ll610/miniconda3/envs/deepsegmentor/lib/python3.5/site-packages/torch/nn/modules/loss.py", line 573, in forward
    reduction=self.reduction)
  File "/home/ll610/miniconda3/envs/deepsegmentor/lib/python3.5/site-packages/torch/nn/functional.py", line 1651, in binary_cross_entropy_with_logits
    loss = input - input * target + max_val + ((-max_val).exp() + (-input - max_val).exp()).log()
RuntimeError: Expected object of type torch.cuda.FloatTensor but found type torch.cuda.LongTensor for argument #2 'other'

```

I encountered this problem while training your model on a customized dataset, would you please help me with that. 
I followed every step as you said but still not working. Have been trying this for 2 days, would really appreciate it if you could help me.

**Comment by Sandeep418** [comment]
change self.criterionSeg(out, self.label) * w to self.criterionSeg(out, self.label.float()) * w and self.criterionSeg(self.outputs[-1], self.label) to  self.criterionSeg(self.outputs[-1], self.label.float())

**Comment by ZheningHuang** [comment]
Thanks, I figured this out several days ago and it works fine. Thanks for your reply anyway!

**Comment by yhlleo** [comment]
Thanks @Sandeep418

**Comment by citystrawman** [comment]
> ```
> Traceback (most recent call last):
>   File "train.py", line 32, in <module>
>     model.optimize_parameters(epoch)   # calculate loss functions, get gradients, update network weights
>   File "/rds/project/t2_vol2/rds-t2-cs056/ll610/Onepiece/zh_data/DeepSegmentor/models/deepcrack_model.py", line 115, in optimize_parameters
>     self.backward()             # calculate gradients for G
>   File "/rds/project/t2_vol2/rds-t2-cs056/ll610/Onepiece/zh_data/DeepSegmentor/models/deepcrack_model.py", line 103, in backward
>     self.loss_side += self.criterionSeg(out, self.label) * w
>   File "/home/ll610/miniconda3/envs/deepsegmentor/lib/python3.5/site-packages/torch/nn/modules/module.py", line 477, in __call__
>     result = self.forward(*input, **kwargs)
>   File "/rds/project/t2_vol2/rds-t2-cs056/ll610/Onepiece/zh_data/DeepSegmentor/models/deepcrack_networks.py", line 103, in forward
>     BCE_loss = self.criterion(inputs, targets)
>   File "/home/ll610/miniconda3/envs/deepsegmentor/lib/python3.5/site-packages/torch/nn/modules/module.py", line 477, in __call__
>     result = self.forward(*input, **kwargs)
>   File "/home/ll610/miniconda3/envs/deepsegmentor/lib/python3.5/site-packages/torch/nn/modules/loss.py", line 573, in forward
>     reduction=self.reduction)
>   File "/home/ll610/miniconda3/envs/deepsegmentor/lib/python3.5/site-packages/torch/nn/functional.py", line 1651, in binary_cross_entropy_with_logits
>     loss = input - input * target + max_val + ((-max_val).exp() + (-input - max_val).exp()).log()
> RuntimeError: Expected object of type torch.cuda.FloatTensor but found type torch.cuda.LongTensor for argument #2 'other'
> ```
> 
> I encountered this problem while training your model on a customized dataset, would you please help me with that. I followed every step as you said but still not working. Have been trying this for 2 days, would really appreciate it if you could help me.

Hi, did you finish all training epochs? I am running the train.py and it has 700 epochs which will take a pretty long time. Must I finish all the epochs or can I just train 200/300 ecpochs?

**Comment by citystrawman** [comment]
> Thanks @Sandeep418

Hi, I am running the train.py and it has 700 epochs which will take a pretty long time. Must I finish all the epochs or can I just train 200/300 ecpochs?
