### ISSUE TITLE
Abnormal html saved output

### ISSUE THREAD

**Issue by giorgiovaccarino** [yhlleo/DeepSegmentor#22]
After running the test on the crack dataset the processed images in the ./results/deepcrack/test_latest/images folder are incorrect (or shifted or locked).

![Schermata del 2021-08-31 12-44-40](https://user-images.githubusercontent.com/25772255/131490112-0d3895ae-1c16-4d90-bde0-0793faab0078.png)
![Schermata del 2021-08-31 12-43-54](https://user-images.githubusercontent.com/25772255/131490130-77e01baa-d4eb-4eb2-a2a3-97413b31d85e.png)

**Comment by yhlleo** [comment]
Hi @giorgiovaccarino, did you check the output images under the output folder? If the output images are abnormal, please check on the save procedure.

**Comment by giorgiovaccarino** [comment]
Hi, yes I checked the images and they are also mismatched. 
I will try to locate the problem in the save process or configuration.
