### ISSUE TITLE
weights balancing for multilabels data

### ISSUE THREAD

**Issue by tanveer6715** [yhlleo/DeepSegmentor#24]
Hi, 
Good work. This code is for binary segmentation. If we have 4 or 5 classes in dataset then how can we calculate the weights of each class?

**Comment by yhlleo** [comment]
Hi @tanveer6715 , thanks. The calculation for multiple classes is also similar: 

Given `[w_1, w_2, ..., w_k]`, where `w_i` refers to the percentage of the frequency of class `i`, we can have the median `w_med = median([w_1, w_2, ..., w_k])`, then the can balance the weights in this manner: `w'_i = w_med/w_i`.
