### ISSUE TITLE
当我在运行train.py遇到了ValueError 好像是 张量不匹配

### ISSUE THREAD

**Issue by Yangyun726** [yhlleo/DeepSegmentor#29]
ValueError: Target size (torch.Size([1, 1, 384, 544])) must be the same as input size (torch.Size([1, 2, 384, 544]))

**Comment by yhlleo** [comment]
@Yangyun726 请问解决了嘛？

**Comment by Yangyun726** [comment]
木有啊



---原始邮件---
发件人: "Yahui ***@***.***&gt;
发送时间: 2022年5月3日(周二) 下午4:03
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [yhlleo/DeepSegmentor] 当我在运行train.py遇到了ValueError 好像是 张量不匹配 (Issue #29)




 
Closed #29.

**Comment by yhlleo** [comment]
> ValueError: Target size (torch.Size([1, 1, 384, 544])) must be the same as input size (torch.Size([1, 2, 384, 544]))

这个应该是loss计算的时候出现的，target tensor 和 predict tensor的shape要一样。

**Comment by Yangyun726** [comment]
是的，但我还是没有调通，你调通了吗



---原始邮件---
发件人: "Yahui ***@***.***&gt;
发送时间: 2022年5月10日(周二) 中午1:49
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [yhlleo/DeepSegmentor] 当我在运行train.py遇到了ValueError 好像是 张量不匹配 (Issue #29)




  
ValueError: Target size (torch.Size([1, 1, 384, 544])) must be the same as input size (torch.Size([1, 2, 384, 544]))
  
这个应该是loss计算的时候出现的，target tensor 和 predict tensor的shape要一样。
