### ISSUE TITLE
how can i achieve your paper's results evaluation?

### ISSUE THREAD

**Issue by chaochon** [yhlleo/DeepSegmentor#3]
thank you for your work and code
i download your code and run the program(without afterprocess including gf and crf). i gain image results and evalues them. but metrics are lower than those of your paper.
 
![image](https://user-images.githubusercontent.com/39073370/67684895-f9bcf400-f9ce-11e9-9afe-efd28ae642b8.png)
what should i do to improve the results. could you give me some advises?
thank you again

**Comment by yhlleo** [comment]
@chaochon ,  I updated the codes for improving the performances of PyTorch implementation. You can find the notice [here](https://github.com/yhlleo/DeepSegmentor/blob/master/eval/README.md).
