### ISSUE TITLE
在运行这个代码时并得到可视化结果需要修改哪些参数，和手动创建哪些文件夹呢

### ISSUE THREAD

**Issue by Eric-is-great** [yhlleo/DeepSegmentor#30]
我想问一个很简单的问题，但这对我来说很困难，我还没有成功运行这个程序
我做了许多尝试比如
visdom的端口号，deault设置为8123（一开始我使用的默认）
自己创建了一个results文件夹，
但是使用sh ./scripts/train_roadnet.sh 0后，虽然GPU可以工作
但是不知道训练的结果在哪里，在checkpoint里面也没有新的数据
只会在DeepSegmentor/checkpoints/roadnet/loss_log多一行如下的数据
================ Training Loss (Tue Apr 12 20:43:56 2022) ================
请问还需要怎样做呢

**Comment by Eric-is-great** [comment]
还有一个疑惑就是
参数display_id的default设置的为1，为什么运行代码时自动变成0了
另外我注意到use_selu的值为0，是否需要使它为1呢

**Comment by yhlleo** [comment]
@Eric-is-great , 很抱歉回复迟了，很高兴你已经解决了问题。

> 我注意到use_selu的值为0，是否需要使它为1呢

如果设置为1， 会使用 SELU activation。我测试的结果，不用好像会好一些。

> 是conda环境的问题，可能问题出在python版本上和pytorch版本上

我过段时间会，把代码升级到更高版本pytorch。

非常感谢反馈～
