### ISSUE TITLE
Error 803

### ISSUE THREAD

**Issue by Francescoipp** [yhlleo/DeepSegmentor#31]
At the end of Step #5:

_RuntimeError: Unexpected error from cudaGetDeviceCount(). Did you run some cuda functions before calling NumCudaDevices() that might have already set an error? Error 803: system has unsupported display driver / cuda driver combination_

**Comment by zzzzmoya** [comment]
Did you resolve this? I also have this problem

**Comment by WALLERR** [comment]
Me, too

**Comment by SanFran-Me** [comment]
> Did you resolve this? I also have this problem

I have met this, too
