### ISSUE TITLE
Is the evaluation process omitted?

### ISSUE THREAD

**Issue by ShamirC** [yhlleo/DeepSegmentor#32]
Hi,
@yhlleo ,
Thanks a lot for your work!
I would like to know if you omit the evaluation process  during training intentionally?
To my knowledge, The evaluation (differs from test procedure) process is used  to evaluate the performance of the network during training, and then select the model weights that got the best performance. So is there any reason to omit the process?

**Comment by yhlleo** [comment]
Yes, this is an example from simple training and testing. It would be better to add the automatic validation during the training procedure.
