### ISSUE TITLE
Can I get the crack of a picture that is taken by myself? 

### ISSUE THREAD

**Issue by citystrawman** [yhlleo/DeepSegmentor#40]
Hi, I am trying to use this code to get the crak of a picture that is taken by myself. 
 I followed the steps described in Readme and I use `sh ./scripts/train_deepcrack.sh <gpu_id>` for training.
Then I would like to do Crack Detection by executing `sh ./scripts/test_deepcrack.sh <gpu_id>`.  
From my perspective I should add the new testing pictures to` datasets/DeepCrack/test_img` and by executing `sh ./scripts/test_deepcrack.sh <gpu_id>` I would get the identified crack images in ` datasets/DeepCrack/test_lab`, however, the program not only requires the images in test_img folder, but also requires images in test_lab, which I thought would be the identified results.
I appreciate if anyone could explain this question to me.

**Comment by yhlleo** [comment]
Hi @citystrawman, sorry for the late response. we add a test example [here](https://github.com/yhlleo/DeepSegmentor/blob/master/test_example.ipynb). Good luck!
