### ISSUE TITLE
How to set up datasets/ folder for "RoadNet"

### ISSUE THREAD

**Issue by GoroYeh-HRI** [yhlleo/DeepSegmentor#41]
Hi, as title,

I downloaded the [Ottawa-dataset](https://github.com/yhlleo/RoadNet?tab=readme-ov-file#11download) here but it looks like this structure:
![image](https://github.com/yhlleo/DeepSegmentor/assets/137837175/48587028-6e67-4be6-a39e-21460688ce09)

How can I make it to follow the Roadnet dataset structure defined [here](https://github.com/yhlleo/DeepSegmentor/blob/master/datasets/README.md#roadnet)?
![image](https://github.com/yhlleo/DeepSegmentor/assets/137837175/27cf4d94-c6e0-4115-a169-27fca1584601)

Should I manually create this folder structure?
Thank you so much!

**Comment by yhlleo** [comment]
@GoroYeh-HRI  You can find the script [here](https://github.com/yhlleo/DeepSegmentor/blob/master/tools/crop_loop.sh) .
