### ISSUE TITLE
[QUESTION] Extract Edge and Centerline Data

### ISSUE THREAD

**Issue by chris-aeviator** [yhlleo/DeepSegmentor#5]
Thanks a ton for your work – I try to create a path from the detected edges to compare it with Open Streetmap Data. However I cannot find out where the edges are created or how to work with them. Can I get the edge pixels separated from the "road surface" and the rest? Same applies to centerline which I'd like to separate from the rest of the result.

I am aware that I will not get a path but I want a result similar to 
![edge](https://user-images.githubusercontent.com/11522213/70303706-ddfd0700-1832-11ea-8db6-19dd265847aa.png)

**Comment by yhlleo** [comment]
Sure, the "edge", "surface" and "centerline" are stored separately in our dataset. Hence, you can use them by your desire. For, example, you can use only the edge data for road edge detection.

**Comment by chris-aeviator** [comment]
@yhlleo thanks four your reply - I am seeking for a **predicted** center & outline

**Comment by yhlleo** [comment]
DeepSegmentor predicts multiple tasks (surface, edge and centerline) in a single map, in which I randomly select green color for edge. If you want to predict centerline only, other stuff would be background (for example, here is black color).

**Comment by chris-aeviator** [comment]
ok - but this would still only end up with pixel's being either black or a shade of green rather than vector-path like data, is that correct? So to get e.g. the outlines I'd rather do image processing (openCV, …) on the result than working with data that DeepSegmentor processes internally?

My goal is to have a moving vehicle's aerial camera image (looking down) self-localize by comparing the detected "roadshapes" it flies over (thus I want the centerline or outline) to a vectorized street-representation of that area on an onboard companion computer.
